#!/bin/sh
title="System Time Setter"
initial=$(zenity --list --title="$title" --height=70 --text "This script will take you through setting your system clock and hardware clock \n\nWould you like to continue?" --radiolist --column "Select" --column "Options" FALSE yes FALSE no)
if [ "$initial" = "no" ]
then exit
fi
if [ "$initial" = "yes" ]
then zones=$(cat /usr/share/zoneinfo/zone.tab | awk '{print $3}' | grep "/" | sed "s/\/.*//g" | sort -ud | sort | awk '{ printf " FALSE ""\0"$0"\0" }')
zone=$(zenity --list --title="$title" --radiolist --text "Select your country/zone." --column Select --column Zone $zones --height=350 --width=300)
subzones=$(cat /usr/share/zoneinfo/zone.tab | awk '{print $3}' | grep "$zone/" | sed "s/$zone\///g" | sort -ud | sort | awk '{ printf " FALSE ""\0"$0"\0" }')
subzone=$(zenity --list --title="$title" --radiolist --text "Select your sub-zone." --column Select --column Zone $subzones --height=350 --width=300)

timedatectl set-timezone $zone/$subzone
password=$(zenity --entry --title="$title" --text "Please enter your password." --hide-text)
echo $password | sudo -S hwclock -w
fi
exit
